name: code-cansu-dev
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - plane-dev
    ports:
      - ${PORT:-6767}:${PORT:-6767}
  

networks:
  plane-dev:
    external: true