name = "code-cansu-dev-backend"
main = "src/index.ts"
compatibility_date = "2024-10-21"
compatibility_flags = ["nodejs_compat"]

[vars]
JUDGE0_BASE_API_URL = "https://judge.cansu.dev"
JUDGE0_AUTHZ_HEADER = "X-Auth-User"
JUDGE0_AUTHN_HEADER = "X-Auth-Token"

[observability]
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "bb50413eb929416993313accb0b321e7"
