// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ArInternalMetadatum struct {
	Key       string
	Value     pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Client struct {
	ID string
}

type CodeAiReaction struct {
	ID        int32
	Code      pgtype.Text
	Reaction  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type DraftSubmission struct {
	ID         int32
	Sourcecode string
	Stdin      pgtype.Text
	Sent       bool
	Createdat  pgtype.Timestamptz
	Updatedat  pgtype.Timestamptz
	Deletedat  pgtype.Timestamptz
}

type Language struct {
	ID         int32
	Name       pgtype.Text
	CompileCmd pgtype.Text
	RunCmd     pgtype.Text
	SourceFile pgtype.Text
	IsArchived pgtype.Bool
}

type SchemaMigration struct {
	Version string
}

type Submission struct {
	ID                                   int32
	SourceCode                           pgtype.Text
	LanguageID                           pgtype.Int4
	Stdin                                pgtype.Text
	ExpectedOutput                       pgtype.Text
	Stdout                               pgtype.Text
	StatusID                             pgtype.Int4
	CreatedAt                            pgtype.Timestamp
	FinishedAt                           pgtype.Timestamp
	Time                                 pgtype.Numeric
	Memory                               pgtype.Int4
	Stderr                               pgtype.Text
	Token                                pgtype.Text
	NumberOfRuns                         pgtype.Int4
	CpuTimeLimit                         pgtype.Numeric
	CpuExtraTime                         pgtype.Numeric
	WallTimeLimit                        pgtype.Numeric
	MemoryLimit                          pgtype.Int4
	StackLimit                           pgtype.Int4
	MaxProcessesAndOrThreads             pgtype.Int4
	EnablePerProcessAndThreadTimeLimit   pgtype.Bool
	EnablePerProcessAndThreadMemoryLimit pgtype.Bool
	MaxFileSize                          pgtype.Int4
	CompileOutput                        pgtype.Text
	ExitCode                             pgtype.Int4
	ExitSignal                           pgtype.Int4
	Message                              pgtype.Text
	WallTime                             pgtype.Numeric
	CompilerOptions                      pgtype.Text
	CommandLineArguments                 pgtype.Text
	RedirectStderrToStdout               pgtype.Bool
	CallbackUrl                          pgtype.Text
	AdditionalFiles                      []byte
	EnableNetwork                        pgtype.Bool
	StartedAt                            pgtype.Timestamp
	QueuedAt                             pgtype.Timestamp
	UpdatedAt                            pgtype.Timestamp
	QueueHost                            pgtype.Text
	ExecutionHost                        pgtype.Text
}

type SubmissionAiReaction struct {
	ID         int32
	Reaction   string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	Judgetoken string
}
