/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TokenImport } from './routes/$token'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TokenRoute = TokenImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$token': {
      id: '/$token'
      path: '/$token'
      fullPath: '/$token'
      preLoaderRoute: typeof TokenImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$token': typeof TokenRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$token': typeof TokenRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$token': typeof TokenRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$token'
  id: '__root__' | '/' | '/$token'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TokenRoute: typeof TokenRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TokenRoute: TokenRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$token"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$token": {
      "filePath": "$token.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
